name: "Build Tool"
permissions:
  contents: write
  discussions: write
on:
  push:
    paths:
      - "build.py"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build Tool
        run: python3 build.py
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          name: "A.R.T-${{ github.run_number }}"
          tag: "CI_BUILD_${{ github.run_number }}"
          body: |
            Build times: ${{ github.run_number }}
            Version: 4
            Note: If you cannot run it, you may need to do "chmod a+x ./*"
            Minimum support: Ubuntu 20.04 (64bit)
          artifacts: "*.zip"
